name: Dockerize and deploy

on:
  release:
    types: [created]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: cthiounn/dares-funathon-2023-sujet-6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  # deployment:
    # runs-on: 'ubuntu-latest'
    # needs: [docker]
    # steps:
      # - uses: actions/checkout@v3
      # - name: Deploy
        # uses: WyriHaximus/github-action-helm3@v3
        # with:
          # exec: helm dependency update .helm-chart/ && helm install .helm-chart/ --generate-name
          # kubeconfig: '${{ secrets.KUBE_CONFIG_DATA }}'